### ISSUE TITLE
如何使用？

### ISSUE THREAD

**Issue by AllanChen** [youxiamotors/object-tracking#1]
1：请问用哪个类可以实现物体的追踪？
2：请问可以追踪视频上面的物体吗？

**Comment by greensea** [comment]
1. 现在的这些代码主要目的还是在于测试各种算法，所以不能直接用来做追踪，也没有提供好用的接口
2. 当然可以追踪视频上的物体，这堆代码就是用来干这件事的

2015-10-15 16:44 GMT+08:00 AllanChan notifications@github.com:

**Comment by AllanChen** [comment]
@greensea 虚心的请教一下您，您这些代码是怎么用的。哪个类是用来追踪的？？感谢感谢！！

**Comment by greensea** [comment]
我把大概流程说一下吧：

main() 函数在 driveassist.cpp 中，其中有不少代码和自动驾驶相关，不过基本上都已经被注释掉了。

进入 main() 后，读取视频的第一帧，并用第一帧来初始化 ObjectTracking 对象，同时传入要追踪的对象在第一帧上的坐标

之后，对视频的每一帧，调用 ObjectTracking 的 detect 方法进行目标跟踪。该方法会返回一个 Rect 对象，表示追踪的目标在这一帧上的坐标

ObjectTracking<T> 中的 T，是一个特征类，目前代码中实现了 HOG 特征、SVD 特征以及颜色直方图特征，这些特征的算法位于 feature_*.cpp 文件中。不同的特征有不同的追踪效果，就目前来看，颜色直方图的效果最好，速度也最快，其次是 HOG，但 HOG 的速度相对颜色直方图来说略慢。SVD 效果最不好，速度也不怎么样。

**Comment by AllanChen** [comment]
@greensea 再次感谢！！ 我看到您的方法的
/// 绘制探测到的目标窗口
    rectangle(imgOrigin, Point(rctObj.x, rctObj.y), Point(rctObj.x + rctObj.width, rctObj.y + rctObj.height), CV_RGB(128, 128, 255), 2);

这段代码，想请教一下您。如果我不追踪窗口，只追踪我想要的区域。如一个窗口或一个胶袋等，改如何更改？

**Comment by AllanChen** [comment]
@greensea 您的代码在opecv 3.0 上运行不了

**Comment by greensea** [comment]
因为用到了 ConDensation 类做粒子滤波，而 OpneCV 3 中把这个类独立出来了，你需要安装 opencv_contrib 才能使用
https://github.com/itseez/opencv_contrib

2015-10-15 19:37 GMT+08:00 AllanChan notifications@github.com:

**Comment by AllanChen** [comment]
@greensea 我已经安装了 opencv_contrib 了，但还不能使用。错误是
![image](https://cloud.githubusercontent.com/assets/1639667/10655258/a9f976ae-78a5-11e5-8d6a-0303dc2e721b.png)

**Comment by greensea** [comment]
是不是贴错图片了？
如果还是失败的话，你可以用“ConDensation OpenCV 3.0”作为关键字搜索一下。你遇到的问题应该就是 OpenCV 3.0 中默认没有包含 ConDensation 类

**Comment by AllanChen** [comment]
对的，就是这个找不到。。但问是网上也没有解决的办法。。我是用opencv3.0的。请问您是用哪个版本的？

**Comment by AllanChen** [comment]
我的目的很简单，就是想追踪一个截图。但网上的都是什么人脸追踪。晕。

**Comment by greensea** [comment]
我用的是 OpenCV 2.4，如果你没有特殊需求的话直接用这个版本就可以。
事实上整个项目都是基于 2.4 版本的，直接使用这个版本会有更好的兼容性，用 3.0 可能还会遇到一些其他的问题

2015-10-22 10:55 GMT+08:00 AllanChan notifications@github.com:

**Comment by AllanChen** [comment]
opencv2.4 有好多的版本？请问您是用？

**Comment by greensea** [comment]
官方发布的稳定版本都可以
2015年10月22日 上午11:03，"AllanChan" notifications@github.com写道：

**Comment by AllanChen** [comment]
opencv 2.4.11 报错
Undefined symbols for architecture x86_64:
  "ot::FeatureHOG::prob(ot::FeatureHOG&)", referenced from:
      ot::ObjectTrackingot::FeatureHOG::prob(cv::Mat) in driveassist.o
  "ot::FeatureHOG::FeatureHOG(cv::Mat&, cv::Rect_<int>)", referenced from:
      ot::ObjectTrackingot::FeatureHOG::updateSubRegions(cv::Mat&, cv::Rect_<int>) in driveassist.o
      ot::ObjectTrackingot::FeatureHOG::prob(cv::Mat) in driveassist.o
  "ot::FeatureHOG::~FeatureHOG()", referenced from:
      ot::ObjectTrackingot::FeatureHOG::updateSubRegions(cv::Mat&, cv::Rect_<int>) in driveassist.o
      std::__1::__split_buffer<ot::FeatureHOG, std::__1::allocator<ot::FeatureHOG>&>::~__split_buffer() in driveassist.o
      std::__1::enable_if<(__is_forward_iteratorot::FeatureHOG*::value) && (is_constructible<ot::FeatureHOG, std::__1::iterator_traits<ot::FeatureHOG*>::reference>::value), void>::type std::__1::vector<ot::FeatureHOG, std::__1::allocator<ot::FeatureHOG> >::assignot::FeatureHOG*(ot::FeatureHOG_, ot::FeatureHOG_) in driveassist.o
      std::__1::vector<ot::FeatureHOG, std::__1::allocator<ot::FeatureHOG> >::deallocate() in driveassist.o
      std::__1::__vector_base<ot::FeatureHOG, std::__1::allocator<ot::FeatureHOG> >::~__vector_base() in driveassist.o
      ot::ObjectTrackingot::FeatureHOG::~ObjectTracking() in driveassist.o
      ot::ObjectTrackingot::FeatureHOG::prob(cv::Mat) in driveassist.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by greensea** [comment]
把你使用的编译命令也发一下

2015-10-22 16:31 GMT+08:00 AllanChan notifications@github.com:
